/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "anaga": {
    "base": "anaga",
    "width": 836,
    "height": 516,
    "fallbackWidth": 800,
    "fallbackHeight": 494,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "auditorio": {
    "base": "auditorio",
    "width": 1920,
    "height": 1223,
    "fallbackWidth": 800,
    "fallbackHeight": 510,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1920,
    "height": 1223,
    "fallbackWidth": 1920,
    "fallbackHeight": 1223,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 1920,
    "height": 1223,
    "fallbackWidth": 1920,
    "fallbackHeight": 1223,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1920,
    "height": 1228,
    "fallbackWidth": 1920,
    "fallbackHeight": 1228,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1281,
    "fallbackWidth": 1920,
    "fallbackHeight": 1281,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1920,
    "height": 1382,
    "fallbackWidth": 800,
    "fallbackHeight": 576,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 1920,
    "height": 1382,
    "fallbackWidth": 800,
    "fallbackHeight": 576,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 1600,
    "height": 1066,
    "fallbackWidth": 1600,
    "fallbackHeight": 1066,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1600,
    "height": 1066,
    "fallbackWidth": 1600,
    "fallbackHeight": 1066,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 1920,
    "height": 1247,
    "fallbackWidth": 800,
    "fallbackHeight": 520,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "la-laguna": {
    "base": "la-laguna",
    "width": 1920,
    "height": 3097,
    "fallbackWidth": 800,
    "fallbackHeight": 1290,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "las-canadas": {
    "base": "las-canadas",
    "width": 1600,
    "height": 1066,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mercado-africa": {
    "base": "mercado-africa",
    "width": 1920,
    "height": 1382,
    "fallbackWidth": 800,
    "fallbackHeight": 576,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mount-teide": {
    "base": "mount-teide",
    "width": 1920,
    "height": 1228,
    "fallbackWidth": 800,
    "fallbackHeight": 512,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 1600,
    "height": 1066,
    "fallbackWidth": 1600,
    "fallbackHeight": 1066,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 1089,
    "fallbackWidth": 1920,
    "fallbackHeight": 1089,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1280,
    "height": 1731,
    "fallbackWidth": 1280,
    "fallbackHeight": 1731,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "plaza-espana": {
    "base": "plaza-espana",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 1920,
    "height": 674,
    "fallbackWidth": 800,
    "fallbackHeight": 281,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "santa-cruz-waterfront": {
    "base": "santa-cruz-waterfront",
    "width": 1920,
    "height": 1281,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 1920,
    "height": 1281,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 1920,
    "height": 1382,
    "fallbackWidth": 800,
    "fallbackHeight": 576,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
